name: '42 Norminette without header check'
on: [push, workflow_dispatch]

jobs:
  norminette-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: grep INVALID_HEADER -B 1 2>&1
