name: '42 Norminette without header check'
on: [push, workflow_dispatch]

jobs:
  norminette-job:
    runs-on: ubuntu-latest
    steps:
      - uses: alexandregv/norminette-action@v3
        with:
          flags: src | grep INVALID_HEADER 2>&1
